# Generated by Django 5.2.4 on 2025-08-04 05:48
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin_user(apps, schema_editor):
    User = apps.get_model('core', 'User')
    UserRole = apps.get_model('core', 'UserRole')

    password = '0502000323Aa'

    admin_user, created = User.objects.get_or_create(
        username='45102910',
        defaults={
            'is_staff': True,
            'is_superuser': True,
        }
    )

    # Only set password if the user was newly created
    if created:
        admin_user.password = make_password(password)
        admin_user.save()

    # Create the corresponding UserRole for the administrator
    UserRole.objects.get_or_create(
        user=admin_user,
        role='administrator', # Use the string value directly as defined in the model
        institution=None
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
